import React from "react";
import { InlineMath, BlockMath } from "react-katex";
import { AttractorCard, AttractorName, GridImage, ImageGrid, ImageLabel, MathBlock, Paragraph, ParamBadge, ParamList, SubTitle } from "../docPrimitives";

// Symmetric Icons — moved verbatim from the Help & About page.
export default function SymmetricIcons() {
  return (
    <>
      <AttractorCard>
        <AttractorName>Symmetric Icons</AttractorName>
        <Paragraph>
          Introduced by mathematicians Michael Field and Martin Golubitsky in their groundbreaking
          book "Symmetry in Chaos" (1992), symmetric icons explore a profound question: can chaotic
          systems produce symmetric patterns? The answer is a beautiful yes. These icons demonstrate
          that order and chaos are not opposites but can coexist in striking visual harmony.
        </Paragraph>
        <ImageGrid>
          <div><GridImage src="/gallery/symmetric-icon-fuzzy-hex-knot.png" alt="Fuzzy Hex Knot" /><ImageLabel>Fuzzy Hex Knot</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-halloween.png" alt="Halloween" /><ImageLabel>Halloween</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-christmas-bow.png" alt="Christmas Bow" /><ImageLabel>Christmas Bow</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-french-glass.png" alt="French Glass" /><ImageLabel>French Glass</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-lace-by-nine.png" alt="Lace by Nine" /><ImageLabel>Lace by Nine</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-chaotic-flower.png" alt="Chaotic Flower" /><ImageLabel>Chaotic Flower</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-emperor-s-cloak.png" alt="Emperor's Cloak" /><ImageLabel>Emperor's Cloak</ImageLabel></div>
          <div><GridImage src="/gallery/symmetric-icon-origami.png" alt="Origami" /><ImageLabel>Origami</ImageLabel></div>
        </ImageGrid>
        <SubTitle>The Mathematics</SubTitle>
        <Paragraph>
          The icons are generated by iterating a complex-valued function derived from the
          logistic map <InlineMath math="f(x) = \lambda x(1-x)" />, one of the simplest systems
          exhibiting chaotic behavior. The function is carefully constructed to preserve
          symmetry while allowing chaotic dynamics:
        </Paragraph>
        <MathBlock>
          <BlockMath math="F(z) = (\lambda + \alpha z\bar{z} + \beta \text{Re}(z^n) + \omega i)z + \gamma\bar{z}^{n-1}" />
        </MathBlock>
        <Paragraph>
          Here <InlineMath math="z" /> is a complex number and <InlineMath math="\bar{z}" /> is
          its complex conjugate. The term <InlineMath math="z\bar{z} = |z|^2" /> represents
          the squared magnitude, while <InlineMath math="\text{Re}(z^n)" /> extracts the real
          part of <InlineMath math="z" /> raised to the <InlineMath math="n" />-th power.
        </Paragraph>
        <SubTitle>Symmetry Groups</SubTitle>
        <Paragraph>
          The parameter <InlineMath math="n" /> (degree) determines the rotational symmetry,
          producing patterns with <InlineMath math="n" />-fold rotational symmetry like regular
          polygons. When <InlineMath math="\omega = 0" />, the attractor exhibits <strong>dihedral
          symmetry</strong> <InlineMath math="D_n" /> (rotational plus reflection symmetry).
          Non-zero <InlineMath math="\omega" /> breaks the reflection symmetry, leaving only
          <strong> cyclic symmetry</strong> <InlineMath math="Z_n" /> (pure rotational symmetry).
        </Paragraph>
        <SubTitle>Parameter Guide</SubTitle>
        <Paragraph>
          Finding beautiful symmetric icons requires careful parameter tuning. Here are the
          constraints and guidelines:
        </Paragraph>
        <Paragraph>
          <strong>Degree (n):</strong> Integer from 3 to 12. Lower values (3-6) produce simpler
          shapes like triangles and hexagons. Higher values (7-12) create more intricate, star-like
          patterns. Most published examples use n = 5, 6, or 7.
        </Paragraph>
        <Paragraph>
          <strong>Lambda (λ):</strong> Typically between -2 and 2. This is the primary "chaos"
          parameter—values near ±1.5 often produce the most interesting results. Values too
          close to 0 may cause the attractor to collapse; values too large cause divergence.
        </Paragraph>
        <Paragraph>
          <strong>Alpha (α):</strong> Usually -2 to 2. Controls the nonlinear scaling based on
          distance from origin. Negative values tend to produce "inward-curling" patterns.
        </Paragraph>
        <Paragraph>
          <strong>Beta (β) and Gamma (γ):</strong> Both typically -2 to 2. These interact with
          the symmetry-preserving terms. Gamma especially affects the "petals" or "arms" of the icon.
        </Paragraph>
        <Paragraph>
          <strong>Omega (ω):</strong> Usually -1 to 1. Set to 0 for reflection symmetry (dihedral).
          Non-zero values create "spinning" asymmetric icons with only rotational symmetry.
        </Paragraph>
        <SubTitle>Example Parameter Sets</SubTitle>
        <Paragraph>
          These known-good combinations produce visually striking icons:
        </Paragraph>
        <MathBlock>
          <BlockMath math="\lambda=1.38, \alpha=-0.42, \beta=0.27, \gamma=0.08, \omega=0.34, n=6" />
          <BlockMath math="\lambda=1.60, \alpha=-1.13, \beta=-0.18, \gamma=0.68, \omega=0.05, n=6" />
          <BlockMath math="\lambda=-1.56, \alpha=1.72, \beta=0.74, \gamma=0.72, \omega=0.26, n=3" />
          <BlockMath math="\lambda=1.46, \alpha=-1.88, \beta=-1.47, \gamma=-0.84, \omega=-0.70, n=4" />
        </MathBlock>
        <SubTitle>Tips for Exploration</SubTitle>
        <Paragraph>
          Start with a known preset and make small adjustments (±0.1) to individual parameters.
          If the attractor disappears or becomes a single point, lambda is likely too extreme.
          If it looks "noisy" without structure, try adjusting alpha and beta. The gamma parameter
          has the most dramatic effect on the overall shape.
        </Paragraph>
        <ParamList>
          <ParamBadge>lambda: -2 to 2</ParamBadge>
          <ParamBadge>alpha: -2 to 2</ParamBadge>
          <ParamBadge>beta: -2 to 2</ParamBadge>
          <ParamBadge>gamma: -2 to 2</ParamBadge>
          <ParamBadge>omega: -1 to 1</ParamBadge>
          <ParamBadge>degree: 3-12</ParamBadge>
        </ParamList>
      </AttractorCard>
    </>
  );
}
