
import React, { useState } from "react";
import styled from "styled-components";
import { GiscusComments } from "../../components/GiscusComments";
import { tokens } from "../../theme/tokens";
import { SYSTEM_PAGES } from "../../content/systemPages";
import { DocLinksContext } from "../../content/docPrimitives";
import {
  mobileQ,
  Section,
  SectionTitle,
  SubTitle,
  Paragraph,
  slug,
  UsageList,
  UsageItem,
  StepNumber,
  CreditSection,
  CreditLink,
} from "../../content/docPrimitives";
import { Icon } from "../../components/ui/Icon";
import { DocsHeader } from "../components/DocsHeader";
import { useDocumentMeta } from "../../seo/useDocumentMeta";
import { pageMetaFor } from "../../seo/meta";

// ============= STYLED COMPONENTS =============

// ============= TAB CONTENT COMPONENTS =============

const AttractorsTab: React.FC = () => (
  <>
    <Section>
      <SectionTitle>Strange Attractors</SectionTitle>
      <Paragraph>
        Strange attractors are patterns that emerge from chaotic dynamical systems.
        Despite the underlying chaos, these systems produce beautiful, structured patterns
        that reveal order within complexity.
      </Paragraph>
    </Section>

    {SYSTEM_PAGES.filter(page => page.group === "attractors").map(page => <page.Body key={page.slug} />)}
  </>
);

const IFSTab: React.FC = () => (
  <>
    <Section>
      <SectionTitle>Iterated Function Systems (IFS)</SectionTitle>
      <Paragraph>
        IFS are a method of constructing fractals using a set of contracting maps.
        The resulting fractal is the unique fixed point of the system, often
        visualized using the "chaos game" - repeatedly applying random
        transformations to a point.
      </Paragraph>
    </Section>

    {SYSTEM_PAGES.filter(page => page.group === "ifs").map(page => <page.Body key={page.slug} />)}
  </>
);

const FractalsTab: React.FC = () => (
  <>
    <Section>
      <SectionTitle>Escape-Time Fractals</SectionTitle>
      <Paragraph>
        Escape-time fractals are generated by iterating a function for each point
        in the complex plane and coloring based on how quickly the iteration
        "escapes" to infinity. The boundary between escaping and non-escaping
        points creates intricate, infinitely detailed patterns.
      </Paragraph>
      <Paragraph>
        The field of complex dynamics began with French mathematicians Pierre Fatou
        and Gaston Julia in the early 20th century. Their work was largely forgotten
        until Benoit Mandelbrot rediscovered it in the 1970s-80s, using computers to
        visualize what Julia and Fatou could only imagine mathematically.
      </Paragraph>
    </Section>

    {SYSTEM_PAGES.filter(page => page.group === "fractals").map(page => <page.Body key={page.slug} />)}
  </>
);

const AboutTab: React.FC = () => (
  <>
    <Section>
      <SectionTitle>About Chaos Iterator</SectionTitle>
      <Paragraph>
        Chaos Iterator is a web-based tool for exploring the beautiful mathematics
        of chaos theory, strange attractors, and fractals. It brings together
        decades of mathematical discovery into an accessible, interactive
        visualization platform.
      </Paragraph>
      <Paragraph>
        This project is <strong>open source</strong> and available on GitHub. Contributions,
        bug reports, and feature requests are welcome!
      </Paragraph>
      <Paragraph>
        <CreditLink
          href="https://github.com/mannuray/Attractor"
          target="_blank"
          rel="noopener noreferrer"
          style={{ fontSize: "16px", fontWeight: 600 }}
        >
          View on GitHub →
        </CreditLink>
      </Paragraph>
    </Section>

    <Section>
      <SectionTitle>Inspiration</SectionTitle>
      <Paragraph>
        This project began with the book <strong>"Symmetry in Chaos"</strong> by
        Michael Field and Martin Golubitsky—a stunning exploration of how chaotic
        systems can produce symmetric, beautiful patterns. The mathematics was
        captivating, but I wanted to see it come alive.
      </Paragraph>
      <Paragraph>
        That search led to discovering{" "}
        <CreditLink href="https://symmetrichaos.sourceforge.net/" target="_blank" rel="noopener noreferrer">
          Symmetry in Chaos
        </CreditLink>, a desktop application that implemented Field and Golubitsky's
        symmetric icon algorithms. The program was beautiful—it generated stunning
        symmetric icons that demonstrated the book's ideas perfectly. The preset
        parameter values, color coding system, and palette definitions used in
        Chaos Iterator's symmetric icons are derived directly from Symmetry in Chaos.
      </Paragraph>
      <Paragraph>
        Unfortunately, like many older software projects, Symmetry in Chaos suffered from
        <em> bit rot</em>. Dependencies became outdated, operating systems moved on,
        and running it became increasingly difficult. The beautiful work was becoming
        inaccessible to new generations of chaos enthusiasts.
      </Paragraph>
      <Paragraph>
        <strong>Chaos Iterator is a modern reimagining of that vision.</strong> Built
        for the web, it runs in any browser without installation. It preserves the
        original symmetric icons from Symmetry in Chaos, while expanding the collection
        to include symmetric quilts (from Field and Golubitsky's book), Clifford
        attractors, De Jong attractors, escape-time fractals like Mandelbrot and
        Julia sets, and many more. New features like real-time parameter editing,
        custom color palettes, and high-resolution export make exploration more
        accessible than ever.
      </Paragraph>
      <Paragraph>
        This project is a tribute to Symmetry in Chaos and the mathematicians who revealed
        the hidden order within chaos. Their work deserves to be seen, explored, and
        appreciated—now and for generations to come.
      </Paragraph>
    </Section>

    <Section>
      <SectionTitle>Credits & References</SectionTitle>

      <SubTitle>Mathematical Foundations</SubTitle>
      <Paragraph>
        <strong>"Symmetry and Chaos"</strong> by Michael Field and Martin Golubitsky -
        The primary reference for Symmetric Icons and Quilts.
      </Paragraph>
      <Paragraph>
        <strong>"Chaos in Wonderland"</strong> by Clifford A. Pickover -
        Source for Fractal Dream attractors and various chaos visualizations.
      </Paragraph>
      <Paragraph>
        <strong>J.C. Sprott</strong> - Research on automatic discovery of strange
        attractors using Lyapunov exponents.
      </Paragraph>

      <SubTitle>Attractor Presets & Parameter Values</SubTitle>
      <Paragraph>
        <CreditLink href="https://paulbourke.net/fractals/clifford/" target="_blank" rel="noopener noreferrer">
          Paul Bourke - Clifford Attractors
        </CreditLink> - Comprehensive documentation on Clifford attractor equations and parameter ranges.
      </Paragraph>
      <Paragraph>
        <CreditLink href="https://paulbourke.net/fractals/peterdejong/" target="_blank" rel="noopener noreferrer">
          Paul Bourke - Peter de Jong Attractors
        </CreditLink> - De Jong attractor formulas, example parameters, and visualization techniques.
      </Paragraph>
      <Paragraph>
        <CreditLink href="https://softologyblog.wordpress.com/2017/03/04/2d-strange-attractors/" target="_blank" rel="noopener noreferrer">
          Softology Blog - 2D Strange Attractors
        </CreditLink> - Extensive collection of attractor presets, parameter values, and exploration techniques
        for Clifford, De Jong, Svensson, Bedhead, and many other attractors.
      </Paragraph>
      <Paragraph>
        <CreditLink href="https://chaos.lookoutjames.co.uk/maths.html" target="_blank" rel="noopener noreferrer">
          Lookout James - Chaos Mathematics
        </CreditLink> - Mathematical explanations and parameter guides for symmetric icons, fractals,
        and strange attractors.
      </Paragraph>
      <Paragraph>
        <CreditLink href="https://paulbourke.net/fractals/symmetryinchaos/" target="_blank" rel="noopener noreferrer">
          Paul Bourke - Symmetry in Chaos
        </CreditLink> - Symmetric Icons implementation details and example parameter sets from
        Field & Golubitsky's work.
      </Paragraph>
      <Paragraph>
        <CreditLink href="https://paulbourke.net/fractals/GumowskiMira/" target="_blank" rel="noopener noreferrer">
          Paul Bourke - Gumowski-Mira
        </CreditLink> - Gumowski-Mira attractor equations and parameter exploration.
      </Paragraph>
      <Paragraph>
        <strong>Jason Rampe</strong> - Creator of the Jason Rampe attractor variants.
      </Paragraph>
      <Paragraph>
        <strong>Simone Conradi</strong> - Creator of the Conradi and Mobius IFS attractors.
      </Paragraph>

      <SubTitle>Historical Attributions</SubTitle>
      <Paragraph>
        <strong>Benoit Mandelbrot</strong> - Discovery and popularization of fractal geometry.
      </Paragraph>
      <Paragraph>
        <strong>Gaston Julia</strong> - Early work on iterative functions in the complex plane.
      </Paragraph>
      <Paragraph>
        <strong>Michel Henon</strong> - The Henon map and attractor.
      </Paragraph>
      <Paragraph>
        <strong>Barry Martin</strong> - The Hopalong attractor.
      </Paragraph>
      <Paragraph>
        <strong>I. Gumowski & C. Mira</strong> - CERN research leading to the Gumowski-Mira attractor.
      </Paragraph>
      <Paragraph>
        <strong>Georges de Rham</strong> - De Rham curves.
      </Paragraph>
    </Section>

    <Section>
      <SectionTitle>Technology</SectionTitle>
      <Paragraph>
        Built with React, TypeScript, and styled-components. Mathematical
        visualizations are rendered using HTML5 Canvas with Web Workers for
        performance. Mathematical formulas rendered with KaTeX.
      </Paragraph>
    </Section>

    <CreditSection>
      <Paragraph style={{ opacity: 0.8, fontSize: "14px", marginBottom: "8px" }}>
        Chaos Iterator - Exploring Order in Chaos
      </Paragraph>
      <CreditLink
        href="https://github.com/mannuray/Attractor"
        target="_blank"
        rel="noopener noreferrer"
        style={{ opacity: 0.6, fontSize: "13px" }}
      >
        github.com/mannuray/Attractor
      </CreditLink>
    </CreditSection>
  </>
);

const HowToUseTab: React.FC = () => (
  <>
    <Section>
      <SectionTitle>Getting Started</SectionTitle>
      <Paragraph>
        Chaos Iterator is a visualization tool for exploring strange attractors,
        iterated function systems (IFS), and escape-time fractals. Each type of
        visualization uses different mathematical equations to create stunning
        patterns from simple rules.
      </Paragraph>
      <UsageList>
        <UsageItem>
          <StepNumber>1</StepNumber>
          <span><strong>Select a Type:</strong> Click the system name at the top (or the System tab) to choose from Attractors, IFS, or Fractals. Each category contains multiple visualization types.</span>
        </UsageItem>
        <UsageItem>
          <StepNumber>2</StepNumber>
          <span><strong>Discovery AI:</strong> Click Hunt in the floating toolbar (or the bottom panel on mobile) to automatically find visually interesting chaotic systems.</span>
        </UsageItem>
        <UsageItem>
          <StepNumber>3</StepNumber>
          <span><strong>Edit Parameters:</strong> Adjust the sliders in the Parameters card of the inspector (Params on mobile) to modify the underlying math in real-time.</span>
        </UsageItem>
        <UsageItem>
          <StepNumber>4</StepNumber>
          <span><strong>Visual FX:</strong> Use the Effects section of the inspector (under Color on mobile) to apply post-processing like Bloom, Grain and Vignette.</span>
        </UsageItem>
        <UsageItem>
          <StepNumber>5</StepNumber>
          <span><strong>Customize Colors:</strong> In the Palette section, click Edit palette to change the color ramp, tone and background.</span>
        </UsageItem>
        <UsageItem>
          <StepNumber>6</StepNumber>
          <span><strong>Save Your Art:</strong> Click Export to save your creation as a high-resolution PNG image.</span>
        </UsageItem>
      </UsageList>
    </Section>

    <Section>
      <SectionTitle>Discovery AI (Smart HUNT)</SectionTitle>
      <Paragraph>
        Finding visually interesting chaotic systems manually can be difficult, as most random parameter combinations result in empty screens or simple points. The **Discovery AI** automates this "exploration" process using a heuristic search algorithm.
      </Paragraph>
      <SubTitle>The Hunting Algorithm</SubTitle>
      <Paragraph>
        When you click the ◈ button, the system triggers a background search process:
      </Paragraph>
      <UsageList>
        <UsageItem>
          <span><strong>1. Fast Simulation:</strong> The AI generates a random seed and simulates a burst of 500,000 points in milliseconds.</span>
        </UsageItem>
        <UsageItem>
          <span><strong>2. Entropy Analysis:</strong> It calculates the "Visual Entropy" (Screen Coverage) of the result.</span>
        </UsageItem>
        <UsageItem>
          <span><strong>3. Golden Ratio Filtering:</strong> The AI automatically rejects "boring" results (too small) and "noise" results (too scattered). It only stops when it finds a structure that hits the "Golden Ratio" of visual complexity (usually 1% to 15% coverage).</span>
        </UsageItem>
      </UsageList>
      <Paragraph>
        You can cancel a hunt at any time by clicking the pulsing <strong>"SCANNING..."</strong> button.
      </Paragraph>
    </Section>

    <Section>
      <SectionTitle>Studio.FX (Post-Processing)</SectionTitle>
      <Paragraph>
        The Studio.FX engine applies cinematic post-processing effects directly to the canvas after the mathematical iteration is complete.
      </Paragraph>
      <UsageList>
        <UsageItem>
          <span><strong>Bloom:</strong> Simulates the glowing aura of bright light sources. It isolates the high-signal parts of the attractor and applies a Gaussian-style bleed, making the patterns feel "alive."</span>
        </UsageItem>
        <UsageItem>
          <span><strong>Exposure:</strong> Adjusts the overall signal intensity. Useful for bringing out delicate structures in sparse attractors.</span>
        </UsageItem>
        <UsageItem>
          <span><strong>Grain:</strong> Adds a fine film-grain texture. This breaks up digital gradients and gives the render a professional, analog photographic feel.</span>
        </UsageItem>
        <UsageItem>
          <span><strong>Vignette:</strong> Subtly darkens the corners of the viewport, focusing the viewer's eye on the chaotic center of the system.</span>
        </UsageItem>
      </UsageList>
    </Section>

    <Section>
      <SectionTitle>Understanding the Parameters</SectionTitle>
      <Paragraph>
        It's not necessary to understand the mathematics to create beautiful images!
        You can experiment by using the presets and adjusting parameters to see how
        changes affect the visualization. However, understanding the math can help
        you predict how parameter changes will affect the output.
      </Paragraph>
      <Paragraph>
        <strong>Scale:</strong> Controls the zoom level of the attractor rendering.
        Smaller values zoom out, larger values zoom in.
      </Paragraph>
      <Paragraph>
        <strong>Iterations:</strong> The number of points calculated. More iterations
        mean more detail but slower rendering.
      </Paragraph>
      <Paragraph>
        <strong>Palette Gamma:</strong> Controls the brightness distribution of the
        color mapping. Lower values brighten shadows, higher values increase contrast.
      </Paragraph>
      <SubTitle>Oversampling (Anti-Aliasing)</SubTitle>
      <Paragraph>
        Chaos Iterator uses <strong>2x oversampling</strong> for smooth, high-quality
        rendering. This means the attractor is computed at twice the display resolution,
        then each 2×2 block of pixels is averaged down to produce the final image.
        This technique eliminates the jagged edges and noise that would otherwise
        appear in fine details, producing smoother gradients and cleaner lines—especially
        visible in the delicate structures of symmetric icons and attractor filaments.
      </Paragraph>
    </Section>
  </>
);

const DiscussTab: React.FC = () => (
  <>
    <Section>
      <SectionTitle>Community Feedback</SectionTitle>
      <Paragraph>
        Have thoughts, ideas, or suggestions? Found a bug or want to request a feature?
        Join the discussion below! Sign in with GitHub to leave a comment.
      </Paragraph>
      <GiscusComments />
    </Section>
  </>
);

// ============= MAIN COMPONENT =============

type GroupId = "getting-started" | "attractors" | "ifs" | "fractals" | "about" | "community";

const GROUPS: { id: GroupId; label: string; chip: string; icon: string; nested: boolean; Body: React.FC }[] = [
  { id: "getting-started", label: "Getting started", chip: "Getting started", icon: "rocket_launch", nested: false, Body: () => <HowToUseTab /> },
  { id: "attractors", label: "Attractors", chip: "Attractors", icon: "grain", nested: true, Body: () => <AttractorsTab /> },
  { id: "ifs", label: "IFS systems", chip: "IFS", icon: "account_tree", nested: true, Body: () => <IFSTab /> },
  { id: "fractals", label: "Fractals", chip: "Fractals", icon: "blur_on", nested: true, Body: () => <FractalsTab /> },
  { id: "about", label: "About & credits", chip: "About", icon: "info", nested: false, Body: () => <AboutTab /> },
  { id: "community", label: "Community", chip: "Community", icon: "forum", nested: false, Body: () => <DiscussTab /> },
];

const Page = styled.div`
  min-height: 100vh;
  background: ${p => p.theme.pageBg};
  color: ${p => p.theme.textHigh};
  font-family: ${tokens.font.ui};
`;

const Layout = styled.div`
  display: grid;
  grid-template-columns: 260px minmax(0, 760px) 200px;
  justify-content: center;
  gap: 40px;
  padding: 32px 24px 80px;
  ${`@media (max-width: 1280px)`} { grid-template-columns: 240px minmax(0, 760px); gap: 32px; }
  ${mobileQ} { display: block; padding: 0 16px 64px; }
`;

const Rail = styled.nav`
  position: sticky; top: 88px; align-self: start; max-height: calc(100vh - 112px); overflow-y: auto;
  display: flex; flex-direction: column; gap: 4px; padding-right: 4px;
  .group-label {
    margin: 16px 0 6px 12px; font: 500 11px/0.875rem ${tokens.font.mono}; letter-spacing: 0.08em;
    text-transform: uppercase; color: ${p => p.theme.textLow};
  }
  .group-label:first-child { margin-top: 0; }
  ${mobileQ} { display: none; }
`;

const RailItem = styled.button<{ $active: boolean }>`
  display: flex; align-items: center; justify-content: space-between; gap: 8px; width: 100%;
  padding: 9px 12px; border-radius: 10px; cursor: pointer; text-align: left;
  background: ${p => (p.$active ? `rgba(${p.theme.primaryRgb}, 0.08)` : "transparent")};
  border: 1px solid ${p => (p.$active ? p.theme.primaryBorder : "transparent")};
  color: ${p => (p.$active ? p.theme.primary : p.theme.textHigh)};
  font: 400 15px/1.25rem ${tokens.font.ui};
  box-shadow: ${p => (p.$active ? p.theme.glowPrimary : "none")};
  &:hover { background: ${p => (p.$active ? `rgba(${p.theme.primaryRgb}, 0.08)` : p.theme.surface)}; }
  .l { display: flex; align-items: center; gap: 10px; }
  .pip { width: 6px; height: 6px; border-radius: 50%; background: ${p => p.theme.primary}; }
`;

const Nested = styled.div`
  margin: 2px 0 6px 18px; padding-left: 10px; border-left: 1px solid ${p => p.theme.hairline};
  display: flex; flex-direction: column; gap: 1px;
`;

const NestedItem = styled.button<{ $active: boolean }>`
  padding: 6px 8px; border-radius: 6px; cursor: pointer; text-align: left;
  background: transparent; border: none;
  color: ${p => (p.$active ? p.theme.primary : p.theme.textMid)};
  font: 400 13px/1.1rem ${tokens.font.ui};
  &:hover { color: ${p => p.theme.textHigh}; background: ${p => p.theme.surface}; }
`;

const Main = styled.main`
  min-width: 0;
`;

const Hero = styled.header`
  margin-bottom: 40px; padding-bottom: 28px; border-bottom: 1px solid ${p => p.theme.hairline};
  .chip {
    display: inline-flex; align-items: center; gap: 8px; padding: 4px 10px; border-radius: 6px;
    background: rgba(${p => p.theme.primaryRgb}, 0.08); border: 1px solid ${p => p.theme.hairline};
    font: 400 12px ${tokens.font.mono}; color: ${p => p.theme.primary};
  }
  .chip::before { content: ""; width: 6px; height: 6px; border-radius: 50%; background: ${p => p.theme.primary}; }
  h1 { margin: 14px 0 10px; font: 700 40px/1.1 ${tokens.font.ui}; letter-spacing: -0.03em; color: ${p => p.theme.textHigh}; }
  p { margin: 0; font: 400 17px/1.6 ${tokens.font.ui}; color: ${p => p.theme.textMid}; }
  ${mobileQ} { margin: 20px 0 28px; h1 { font-size: 30px; } p { font-size: 15px; } }
`;

const Chips = styled.div`
  display: none;
  ${mobileQ} {
    display: flex; gap: 8px; overflow-x: auto; position: sticky; top: 52px; z-index: 20;
    margin: 0 -16px; padding: 10px 16px; scrollbar-width: none;
    background: ${p => p.theme.glassBar}; backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid ${p => p.theme.hairline};
    &::-webkit-scrollbar { display: none; }
  }
`;

const Chip = styled.button<{ $active: boolean }>`
  flex-shrink: 0; display: inline-flex; align-items: center; gap: 6px; min-height: 40px; padding: 0 14px;
  border-radius: ${tokens.radius.full}; cursor: pointer; white-space: nowrap;
  background: ${p => (p.$active ? `rgba(${p.theme.primaryRgb}, 0.12)` : p.theme.surface)};
  border: 1px solid ${p => (p.$active ? p.theme.primaryBorder : p.theme.hairline)};
  color: ${p => (p.$active ? p.theme.primary : p.theme.textHigh)};
  font: 500 13px ${tokens.font.ui};
  &::before { content: ""; width: 6px; height: 6px; border-radius: 50%; display: ${p => (p.$active ? "block" : "none")}; background: ${p => p.theme.primary}; }
`;

const Group = styled.div`
  scroll-margin-top: 72px;
  ${mobileQ} { scroll-margin-top: 120px; }
`;

const Outline = styled.aside`
  position: sticky; top: 88px; align-self: start;
  .t { margin: 0 0 10px; font: 500 11px/0.875rem ${tokens.font.mono}; letter-spacing: 0.08em; text-transform: uppercase; color: ${p => p.theme.textLow}; }
  ul { list-style: none; margin: 0; padding: 0 0 0 12px; border-left: 1px solid ${p => p.theme.hairline}; display: flex; flex-direction: column; gap: 8px; }
  .top {
    margin-top: 20px; background: none; border: none; padding: 0; cursor: pointer;
    font: 400 12px ${tokens.font.mono}; color: ${p => p.theme.primary};
  }
  ${`@media (max-width: 1280px)`} { display: none; }
`;

const OutlineLink = styled.button<{ $active: boolean }>`
  background: none; border: none; padding: 0; cursor: pointer; text-align: left;
  font: 400 13px/1.25rem ${tokens.font.ui};
  color: ${p => (p.$active ? p.theme.primary : p.theme.textMid)};
  &:hover { color: ${p => p.theme.textHigh}; }
`;

const Footer = styled.footer`
  margin-top: 48px; padding-top: 20px; border-top: 1px solid ${p => p.theme.hairline};
  font: 400 12px ${tokens.font.mono}; color: ${p => p.theme.textLow};
`;

// Mount the comments iframe only when the Community section is close to the viewport.
const LazyComments: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const ref = React.useRef<HTMLDivElement>(null);
  const [show, setShow] = useState(typeof window === "undefined" || !("IntersectionObserver" in window));
  React.useEffect(() => {
    if (show || !ref.current) return;
    const io = new IntersectionObserver(entries => {
      if (entries.some(e => e.isIntersecting)) { setShow(true); io.disconnect(); }
    }, { rootMargin: "600px" });
    io.observe(ref.current);
    return () => io.disconnect();
  }, [show]);
  return <div ref={ref}>{show ? children : <div style={{ minHeight: 400 }} />}</div>;
};

const linkForTitle = (title: string) => {
  const page = SYSTEM_PAGES.find(p => p.title === title);
  return page ? `/systems/${page.slug}` : undefined;
};

const Info: React.FC = () => {
  useDocumentMeta(pageMetaFor("/info"));
  const [active, setActive] = useState<GroupId>("getting-started");
  const [activeSystem, setActiveSystem] = useState<string | null>(null);
  const [systems, setSystems] = useState<Partial<Record<GroupId, string[]>>>({});
  const groupRefs = React.useRef<Partial<Record<GroupId, HTMLDivElement | null>>>({});

  // Build the nested system links from the rendered system headings, so content stays the source of truth.
  React.useEffect(() => {
    const next: Partial<Record<GroupId, string[]>> = {};
    for (const g of GROUPS) {
      const el = groupRefs.current[g.id];
      if (g.nested && el) {
        next[g.id] = Array.from(el.querySelectorAll<HTMLElement>("[data-system]")).map(h => h.dataset.system!);
      }
    }
    setSystems(next);
  }, []);

  // After a rail click, keep that item highlighted until the user scrolls themselves; otherwise a
  // short last section (which can't reach the top) would snap the highlight back to its neighbour.
  const navLock = React.useRef(false);

  // Track which group / system is in view.
  React.useEffect(() => {
    const release = () => { navLock.current = false; };
    const releaseOnKeys = (e: KeyboardEvent) => {
      if (["ArrowUp", "ArrowDown", "PageUp", "PageDown", "Home", "End", " "].includes(e.key)) release();
    };
    window.addEventListener("wheel", release, { passive: true });
    window.addEventListener("touchmove", release, { passive: true });
    window.addEventListener("keydown", releaseOnKeys);
    const onScroll = () => {
      if (navLock.current) return;
      const y = 140;
      let current: GroupId = GROUPS[0].id;
      for (const g of GROUPS) {
        const el = groupRefs.current[g.id];
        if (el && el.getBoundingClientRect().top <= y) current = g.id;
      }
      setActive(current);
      let sys: string | null = null;
      document.querySelectorAll<HTMLElement>("[data-system]").forEach(h => {
        if (h.getBoundingClientRect().top <= y) sys = h.dataset.system!;
      });
      setActiveSystem(sys);
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => {
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("wheel", release);
      window.removeEventListener("touchmove", release);
      window.removeEventListener("keydown", releaseOnKeys);
    };
  }, []);

  const goGroup = (id: GroupId) => {
    navLock.current = true;
    setActive(id);
    groupRefs.current[id]?.scrollIntoView({ behavior: "smooth", block: "start" });
  };
  const goSystem = (group: GroupId, name: string) => {
    navLock.current = true;
    setActive(group);
    setActiveSystem(name);
    document.getElementById(`system-${slug(name)}`)?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const docGroups = GROUPS.slice(0, 4);
  const projectGroups = GROUPS.slice(4);

  const railItem = (g: (typeof GROUPS)[number]) => (
    <React.Fragment key={g.id}>
      <RailItem type="button" $active={active === g.id} aria-current={active === g.id ? "true" : undefined} onClick={() => goGroup(g.id)}>
        <span className="l">{active === g.id && <span className="pip" />}{g.label}</span>
        {active === g.id && <Icon name="chevronRight" size={16} />}
      </RailItem>
      {g.nested && active === g.id && (systems[g.id]?.length ?? 0) > 0 && (
        <Nested aria-label={`${g.label} systems`}>
          {systems[g.id]!.map(name => (
            <NestedItem key={name} type="button" $active={activeSystem === name} onClick={() => goSystem(g.id, name)}>{name}</NestedItem>
          ))}
        </Nested>
      )}
    </React.Fragment>
  );

  return (
    <Page>
      <DocsHeader />

      <Layout>
        <Rail aria-label="Documentation">
          <div className="group-label">Documentation</div>
          {docGroups.map(railItem)}
          <div className="group-label">Project &amp; community</div>
          {projectGroups.map(railItem)}
        </Rail>

        <Main>
          <Chips role="navigation" aria-label="Sections">
            {GROUPS.map(g => (
              <Chip key={g.id} type="button" $active={active === g.id} onClick={() => goGroup(g.id)}>{g.chip}</Chip>
            ))}
          </Chips>

          <Hero>
            <span className="chip">Chaos Iterator documentation</span>
            <h1>Help &amp; About</h1>
            <p>How to use the studio, the mathematics behind every system, a gallery of renders, and the people and ideas behind the project.</p>
          </Hero>

          <DocLinksContext.Provider value={linkForTitle}>
          {GROUPS.map(g => (
            <Group key={g.id} id={g.id} ref={el => { groupRefs.current[g.id] = el; }}>
              {g.id === "community" ? <LazyComments><g.Body /></LazyComments> : <g.Body />}
            </Group>
          ))}
          </DocLinksContext.Provider>

          <Footer>Chaos Iterator — strange attractors, IFS and fractals in the browser.</Footer>
        </Main>

        <Outline aria-label="On this page">
          <p className="t">On this page</p>
          <ul>
            {GROUPS.map(g => (
              <li key={g.id}><OutlineLink type="button" $active={active === g.id} onClick={() => goGroup(g.id)}>{g.label}</OutlineLink></li>
            ))}
          </ul>
          <button type="button" className="top" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Scroll to top ↑</button>
        </Outline>
      </Layout>
    </Page>
  );
};

export default Info;
