#!/usr/bin/env node
// Bundles the server handlers in src/server/ into self-contained CommonJS files that Vercel
// loads directly: proxy.js (Routing Middleware) and api/og.js (share-card function).
// Vercel would otherwise transpile the .ts sources file by file with this repo's tsconfig
// ("module": "esnext", enforced by CRA) and Node, seeing no "type": "module", fails to load
// them ("Cannot use import statement outside a module").
//
//   node scripts/build-server.mjs          write the bundles (commit them)
//   node scripts/build-server.mjs --check  exit 1 if the committed bundles are stale
import { build } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const banner = "// GENERATED by scripts/build-server.mjs from src/server/. Do not edit; run `npm run build:server`.";

const targets = [
  { entry: "src/server/proxy.ts", out: "proxy.js", external: [] },
  // sharp is a native module: required at runtime, traced into the function by Vercel.
  { entry: "src/server/og.ts", out: "api/og.js", external: ["sharp"] },
];

let stale = [];
for (const t of targets) {
  const result = await build({
    entryPoints: [path.join(root, t.entry)],
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node20",
    external: t.external,
    banner: { js: banner },
    loader: { ".js": "jsx" },
    define: { "process.env.NODE_ENV": '"production"' },
    write: false,
    logLevel: "warning",
    legalComments: "none",
  });
  const code = result.outputFiles[0].text;
  const file = path.join(root, t.out);
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== code) stale.push(t.out);
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, code);
    console.log(`wrote ${t.out} (${(code.length / 1024).toFixed(0)} KB)`);
  }
}

if (stale.length) {
  console.error(`stale server bundle(s): ${stale.join(", ")} — run \`npm run build:server\` and commit.`);
  process.exit(1);
}
