// GENERATED by scripts/build-server.mjs from src/server/. Do not edit; run `npm run build:server`.
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/server/og.ts
var og_exports = {};
__export(og_exports, {
  GET: () => GET
});
module.exports = __toCommonJS(og_exports);

// src/Parametersets.ts
var symmetricIconDataString = `[
  {
    "name": "Halloween",
    "alpha": 5,
    "betha": 1.5,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.7,
    "degree": 6,
    "npdegree": 0,
    "scale": 0.6,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 133,
        "green": 51,
        "blue": 18
      },
      {
        "position": 0.0189474,
        "red": 206,
        "green": 230,
        "blue": 201
      },
      {
        "position": 0.0378947,
        "red": 38,
        "green": 38,
        "blue": 68
      },
      {
        "position": 0.0589474,
        "red": 255,
        "green": 115,
        "blue": 0
      },
      {
        "position": 0.0778947,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.128421,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.157895,
        "red": 0,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.210526,
        "red": 248,
        "green": 8,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 0,
        "blue": 0
      }
    ]
  },
  {
    "name": "Mayan Bracelet",
    "alpha": 1,
    "betha": -0.1,
    "gamma": 0.167,
    "delta": 0,
    "omega": 0,
    "lambda": -2.08,
    "degree": 7,
    "npdegree": 0,
    "scale": 0.4,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.136842,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.189474,
        "red": 86,
        "green": 255,
        "blue": 89
      },
      {
        "position": 0.231579,
        "red": 0,
        "green": 0,
        "blue": 212
      },
      {
        "position": 0.425263,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Wild Chaos",
    "alpha": -1,
    "betha": -0.02,
    "gamma": -0.75,
    "delta": 0,
    "omega": 0.04,
    "lambda": 1.5,
    "degree": 3,
    "npdegree": 24,
    "scale": 0.4,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0620253,
        "red": 0,
        "green": 0,
        "blue": 221
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Triple Clam",
    "alpha": -1,
    "betha": 0.1,
    "gamma": -0.82,
    "delta": 0,
    "omega": 0.12,
    "lambda": 1.56,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.38,
    "palGamma": 0.3,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0291667,
        "red": 230,
        "green": 233,
        "blue": 255
      },
      {
        "position": 0.0833333,
        "red": 230,
        "green": 255,
        "blue": 138
      },
      {
        "position": 0.135417,
        "red": 233,
        "green": 151,
        "blue": 0
      },
      {
        "position": 0.183333,
        "red": 255,
        "green": 202,
        "blue": 104
      },
      {
        "position": 0.233333,
        "red": 255,
        "green": 123,
        "blue": 0
      },
      {
        "position": 0.377083,
        "red": 240,
        "green": 77,
        "blue": 134
      },
      {
        "position": 1,
        "red": 255,
        "green": 0,
        "blue": 0
      }
    ]
  },
  {
    "name": "Emperor's Cloak",
    "alpha": 1.806,
    "betha": 0,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -1.806,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.59,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0189873,
        "red": 255,
        "green": 233,
        "blue": 255
      },
      {
        "position": 0.0721519,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.187342,
        "red": 246,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.420253,
        "red": 0,
        "green": 214,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "The Trampoline",
    "alpha": -1,
    "betha": 0.1,
    "gamma": -0.82,
    "delta": 0,
    "omega": 0,
    "lambda": 1.56,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.38,
    "palGamma": 0.3,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.08,
        "red": 214,
        "green": 44,
        "blue": 134
      },
      {
        "position": 0.189474,
        "red": 255,
        "green": 230,
        "blue": 0
      },
      {
        "position": 0.235789,
        "red": 0,
        "green": 165,
        "blue": 0
      },
      {
        "position": 0.362105,
        "red": 187,
        "green": 11,
        "blue": 178
      },
      {
        "position": 0.418947,
        "red": 0,
        "green": 48,
        "blue": 190
      },
      {
        "position": 0.549474,
        "red": 60,
        "green": 96,
        "blue": 205
      },
      {
        "position": 0.591579,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Yin Yang",
    "alpha": 10,
    "betha": -12,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.195,
    "degree": 3,
    "npdegree": 0,
    "scale": 1.2,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.128421,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 1,
        "red": 0,
        "green": 0,
        "blue": 0
      }
    ]
  },
  {
    "name": "Fish and Eye",
    "alpha": 10,
    "betha": -12,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.18,
    "degree": 3,
    "npdegree": 0,
    "scale": 1.2,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.329114,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Swirling Streamers",
    "alpha": 2,
    "betha": 0,
    "gamma": 1,
    "delta": 0,
    "omega": 0.1,
    "lambda": -1.86,
    "degree": 4,
    "npdegree": 0,
    "scale": 0.54,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 50,
        "green": 62,
        "blue": 115
      },
      {
        "position": 0.0333333,
        "red": 24,
        "green": 110,
        "blue": 172
      },
      {
        "position": 0.0589474,
        "red": 140,
        "green": 135,
        "blue": 214
      },
      {
        "position": 0.0854167,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.158333,
        "red": 160,
        "green": 0,
        "blue": 160
      },
      {
        "position": 0.216667,
        "red": 255,
        "green": 154,
        "blue": 181
      },
      {
        "position": 1,
        "red": 255,
        "green": 154,
        "blue": 183
      }
    ]
  },
  {
    "name": "Lace by Nine",
    "alpha": 8,
    "betha": -0.7,
    "gamma": 1,
    "delta": -0.9,
    "omega": 0,
    "lambda": -2.5,
    "degree": 9,
    "npdegree": 0,
    "scale": 0.75,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 15,
        "green": 86,
        "blue": 71
      },
      {
        "position": 0.0863158,
        "red": 190,
        "green": 221,
        "blue": 165
      },
      {
        "position": 0.134737,
        "red": 215,
        "green": 197,
        "blue": 126
      },
      {
        "position": 0.197895,
        "red": 172,
        "green": 127,
        "blue": 60
      },
      {
        "position": 0.341053,
        "red": 224,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.494737,
        "red": 255,
        "green": 153,
        "blue": 0
      },
      {
        "position": 0.658947,
        "red": 247,
        "green": 214,
        "blue": 158
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Gothic Medallion",
    "alpha": 10,
    "betha": -12.3,
    "gamma": 0.75,
    "delta": 0.02,
    "omega": 0,
    "lambda": -2.38,
    "degree": 5,
    "npdegree": 1,
    "scale": 1.1,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.115789,
        "red": 119,
        "green": 135,
        "blue": 0
      },
      {
        "position": 0.178947,
        "red": 0,
        "green": 209,
        "blue": 0
      },
      {
        "position": 0.223158,
        "red": 0,
        "green": 0,
        "blue": 255
      },
      {
        "position": 0.273684,
        "red": 0,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.334737,
        "red": 210,
        "green": 255,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Sand Dollar",
    "alpha": 2,
    "betha": 0.2,
    "gamma": 0.1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.34,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.49,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 169,
        "green": 64,
        "blue": 43
      },
      {
        "position": 0.0652632,
        "red": 255,
        "green": 239,
        "blue": 167
      },
      {
        "position": 0.183158,
        "red": 185,
        "green": 137,
        "blue": 83
      },
      {
        "position": 0.208421,
        "red": 194,
        "green": 65,
        "blue": 0
      },
      {
        "position": 0.237895,
        "red": 0,
        "green": 0,
        "blue": 199
      },
      {
        "position": 0.277895,
        "red": 0,
        "green": 153,
        "blue": 0
      },
      {
        "position": 0.442105,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Pentagon Attractor",
    "alpha": -2,
    "betha": 0,
    "gamma": -0.5,
    "delta": 0,
    "omega": 0,
    "lambda": 2.6,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.38,
    "palGamma": 0.3,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 253,
        "green": 253,
        "blue": 255
      },
      {
        "position": 0.0568421,
        "red": 219,
        "green": 240,
        "blue": 228
      },
      {
        "position": 0.0842105,
        "red": 155,
        "green": 217,
        "blue": 179
      },
      {
        "position": 0.111579,
        "red": 187,
        "green": 229,
        "blue": 169
      },
      {
        "position": 0.136842,
        "red": 255,
        "green": 255,
        "blue": 149
      },
      {
        "position": 0.16,
        "red": 74,
        "green": 162,
        "blue": 125
      },
      {
        "position": 0.187368,
        "red": 152,
        "green": 230,
        "blue": 229
      },
      {
        "position": 0.242105,
        "red": 68,
        "green": 116,
        "blue": 199
      },
      {
        "position": 0.32,
        "red": 169,
        "green": 99,
        "blue": 169
      },
      {
        "position": 0.423158,
        "red": 0,
        "green": 162,
        "blue": 0
      },
      {
        "position": 1,
        "red": 0,
        "green": 165,
        "blue": 0
      }
    ]
  },
  {
    "name": "Chaotic Flower",
    "alpha": 5,
    "betha": -1.9,
    "gamma": 1,
    "delta": 0,
    "omega": 0.188,
    "lambda": -2.5,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.7,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.16,
        "red": 249,
        "green": 93,
        "blue": 116
      },
      {
        "position": 0.195789,
        "red": 246,
        "green": 0,
        "blue": 185
      },
      {
        "position": 0.237895,
        "red": 255,
        "green": 248,
        "blue": 253
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Mercedes Star",
    "alpha": -2.1,
    "betha": 0,
    "gamma": 1,
    "delta": 1,
    "omega": 0,
    "lambda": 1,
    "degree": 3,
    "npdegree": 1,
    "scale": 0.48,
    "palGamma": 0.2,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 224,
        "green": 224,
        "blue": 184
      },
      {
        "position": 0.134737,
        "red": 135,
        "green": 135,
        "blue": 135
      },
      {
        "position": 0.166316,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.208421,
        "red": 43,
        "green": 138,
        "blue": 147
      },
      {
        "position": 0.258947,
        "red": 0,
        "green": 0,
        "blue": 187
      },
      {
        "position": 0.303158,
        "red": 166,
        "green": 166,
        "blue": 255
      },
      {
        "position": 0.349474,
        "red": 255,
        "green": 255,
        "blue": 200
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 187
      }
    ]
  },
  {
    "name": "Kachina Dolls",
    "alpha": -2.5,
    "betha": 0,
    "gamma": 0.9,
    "delta": 0,
    "omega": 0,
    "lambda": 2.409,
    "degree": 23,
    "npdegree": 0,
    "scale": 0.53,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.0168421,
        "red": 228,
        "green": 228,
        "blue": 243
      },
      {
        "position": 0.0294737,
        "red": 192,
        "green": 180,
        "blue": 235
      },
      {
        "position": 0.0568421,
        "red": 212,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.101053,
        "red": 0,
        "green": 167,
        "blue": 0
      },
      {
        "position": 0.117895,
        "red": 0,
        "green": 0,
        "blue": 165
      },
      {
        "position": 0.187368,
        "red": 249,
        "green": 249,
        "blue": 4
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Sunflower",
    "alpha": 1.5,
    "betha": -0.014,
    "gamma": 0.002,
    "delta": -0.02,
    "omega": 0,
    "lambda": -2.225,
    "degree": 57,
    "npdegree": 0,
    "scale": 0.45,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.0378947,
        "red": 255,
        "green": 234,
        "blue": 0
      },
      {
        "position": 0.210526,
        "red": 255,
        "green": 26,
        "blue": 0
      },
      {
        "position": 0.338947,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.378947,
        "red": 0,
        "green": 0,
        "blue": 255
      },
      {
        "position": 0.503158,
        "red": 0,
        "green": 217,
        "blue": 0
      },
      {
        "position": 1,
        "red": 0,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Santa Chiara Icon",
    "alpha": -2.5,
    "betha": -0.2,
    "gamma": 0.81,
    "delta": 0,
    "omega": 0,
    "lambda": 2.409,
    "degree": 24,
    "npdegree": 0,
    "scale": 0.53,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.0463158,
        "red": 96,
        "green": 106,
        "blue": 34
      },
      {
        "position": 0.08,
        "red": 25,
        "green": 35,
        "blue": 169
      },
      {
        "position": 0.143158,
        "red": 125,
        "green": 0,
        "blue": 129
      },
      {
        "position": 0.212632,
        "red": 247,
        "green": 0,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "French Glass",
    "alpha": 3,
    "betha": -16.79,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.05,
    "degree": 9,
    "npdegree": 0,
    "scale": 0.7,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 0,
        "green": 205,
        "blue": 0
      },
      {
        "position": 0.0357895,
        "red": 128,
        "green": 99,
        "blue": 156
      },
      {
        "position": 0.0505263,
        "red": 157,
        "green": 81,
        "blue": 162
      },
      {
        "position": 0.138947,
        "red": 255,
        "green": 204,
        "blue": 0
      },
      {
        "position": 0.189474,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 250
      }
    ]
  },
  {
    "name": "The Pentacle",
    "alpha": 2.32,
    "betha": 0,
    "gamma": 0.75,
    "delta": 0,
    "omega": 0,
    "lambda": -2.32,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.49,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 210
      },
      {
        "position": 0.0757895,
        "red": 247,
        "green": 247,
        "blue": 195
      },
      {
        "position": 0.0968421,
        "red": 199,
        "green": 190,
        "blue": 126
      },
      {
        "position": 0.117895,
        "red": 177,
        "green": 215,
        "blue": 145
      },
      {
        "position": 0.138947,
        "red": 120,
        "green": 165,
        "blue": 217
      },
      {
        "position": 0.157895,
        "red": 56,
        "green": 95,
        "blue": 221
      },
      {
        "position": 0.178947,
        "red": 139,
        "green": 141,
        "blue": 225
      },
      {
        "position": 0.244211,
        "red": 150,
        "green": 29,
        "blue": 156
      },
      {
        "position": 0.355789,
        "red": 205,
        "green": 38,
        "blue": 214
      },
      {
        "position": 1,
        "red": 223,
        "green": 34,
        "blue": 223
      }
    ]
  },
  {
    "name": "Star of David",
    "alpha": 1,
    "betha": -0.04,
    "gamma": 0.14,
    "delta": 0.088,
    "omega": 0,
    "lambda": -2.42,
    "degree": 6,
    "npdegree": 0,
    "scale": 0.33,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 132,
        "green": 0,
        "blue": 162
      },
      {
        "position": 0.0147368,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.04,
        "red": 0,
        "green": 179,
        "blue": 199
      },
      {
        "position": 0.0989474,
        "red": 104,
        "green": 125,
        "blue": 185
      },
      {
        "position": 0.128421,
        "red": 192,
        "green": 191,
        "blue": 210
      },
      {
        "position": 0.162105,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.197895,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.233684,
        "red": 0,
        "green": 192,
        "blue": 0
      },
      {
        "position": 1,
        "red": 0,
        "green": 201,
        "blue": 0
      }
    ]
  },
  {
    "name": "Golden Flintstone",
    "alpha": -2.5,
    "betha": 0,
    "gamma": 0.9,
    "delta": 0,
    "omega": 0,
    "lambda": 2.5,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.37,
    "palGamma": 0.45,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.0357895,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.115789,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.157895,
        "red": 0,
        "green": 0,
        "blue": 255
      },
      {
        "position": 0.176842,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.195789,
        "red": 154,
        "green": 0,
        "blue": 154
      },
      {
        "position": 0.324211,
        "red": 0,
        "green": 221,
        "blue": 0
      },
      {
        "position": 0.433684,
        "red": 255,
        "green": 120,
        "blue": 120
      },
      {
        "position": 1,
        "red": 255,
        "green": 123,
        "blue": 123
      }
    ]
  },
  {
    "name": "Trinity Alpha",
    "alpha": -1,
    "betha": 0.03,
    "gamma": -0.8,
    "delta": 0,
    "omega": 0,
    "lambda": 1.455,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.4,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.0652632,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.138947,
        "red": 0,
        "green": 203,
        "blue": 0
      },
      {
        "position": 0.151579,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Trinity Beta",
    "alpha": -1,
    "betha": 0.03,
    "gamma": -0.8,
    "delta": -0.025,
    "omega": 0,
    "lambda": 1.455,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.4,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.0989474,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.162105,
        "red": 0,
        "green": 208,
        "blue": 0
      },
      {
        "position": 0.216842,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Sixteen Fold",
    "alpha": -2.5,
    "betha": -0.1,
    "gamma": 0.9,
    "delta": 0,
    "omega": 0,
    "lambda": 2.39,
    "degree": 16,
    "npdegree": 0,
    "scale": 0.54,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.128421,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.237895,
        "red": 117,
        "green": 0,
        "blue": 115
      },
      {
        "position": 0.4,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Sixteen Fold Twist",
    "alpha": -2.5,
    "betha": -0.1,
    "gamma": 0.9,
    "delta": 0,
    "omega": -0.15,
    "lambda": 2.39,
    "degree": 16,
    "npdegree": 0,
    "scale": 0.54,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.216842,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.273684,
        "red": 111,
        "green": 0,
        "blue": 87
      },
      {
        "position": 0.431579,
        "red": 255,
        "green": 255,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 0
      }
    ]
  },
  {
    "name": "Blue Trinity",
    "alpha": -1,
    "betha": 0.1,
    "gamma": -0.8,
    "delta": 0,
    "omega": 0,
    "lambda": 1.5,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.4,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.224051,
        "red": 0,
        "green": 0,
        "blue": 221
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Trinity in Red",
    "alpha": -1,
    "betha": 0.1,
    "gamma": -0.805,
    "delta": 0,
    "omega": 0,
    "lambda": 1.5,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.4,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 192,
        "green": 205,
        "blue": 0
      },
      {
        "position": 0.0821053,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.174737,
        "red": 0,
        "green": 172,
        "blue": 46
      },
      {
        "position": 0.233684,
        "red": 0,
        "green": 0,
        "blue": 185
      },
      {
        "position": 0.503158,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Pure Chaos",
    "alpha": 9.5,
    "betha": -12,
    "gamma": 1,
    "delta": 0.22,
    "omega": 0.47,
    "lambda": -2.3,
    "degree": 3,
    "npdegree": 5,
    "scale": 0.85,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0329114,
        "red": 0,
        "green": 0,
        "blue": 221
      },
      {
        "position": 0.0670886,
        "red": 230,
        "green": 114,
        "blue": 197
      },
      {
        "position": 0.140506,
        "red": 176,
        "green": 134,
        "blue": 255
      },
      {
        "position": 0.201266,
        "red": 0,
        "green": 50,
        "blue": 111
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "12-Spoke Wheel",
    "alpha": 4,
    "betha": 1.5,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.6,
    "degree": 12,
    "npdegree": 0,
    "scale": 0.6,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0357895,
        "red": 248,
        "green": 243,
        "blue": 255
      },
      {
        "position": 0.0968421,
        "red": 84,
        "green": 177,
        "blue": 51
      },
      {
        "position": 0.109474,
        "red": 176,
        "green": 122,
        "blue": 40
      },
      {
        "position": 0.136842,
        "red": 209,
        "green": 102,
        "blue": 36
      },
      {
        "position": 0.227368,
        "red": 0,
        "green": 0,
        "blue": 221
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "36-Spoke Wheel",
    "alpha": 3.2,
    "betha": 1.2,
    "gamma": -1.75,
    "delta": 0,
    "omega": 0,
    "lambda": -2.57,
    "degree": 36,
    "npdegree": 0,
    "scale": 0.55,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0547368,
        "red": 96,
        "green": 96,
        "blue": 96
      },
      {
        "position": 0.0673684,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.0989474,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.296842,
        "red": 0,
        "green": 0,
        "blue": 221
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Christmas Bow",
    "alpha": 2.2,
    "betha": 0.4,
    "gamma": 0.05,
    "delta": 0,
    "omega": 0,
    "lambda": -2.34,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.5,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0336842,
        "red": 89,
        "green": 186,
        "blue": 255
      },
      {
        "position": 0.0589474,
        "red": 175,
        "green": 0,
        "blue": 85
      },
      {
        "position": 0.124211,
        "red": 0,
        "green": 178,
        "blue": 131
      },
      {
        "position": 0.162105,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.541053,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Fuzzy Hex Knot",
    "alpha": 1.807,
    "betha": -0.07,
    "gamma": 1.08,
    "delta": 0,
    "omega": 0,
    "lambda": -1.806,
    "degree": 6,
    "npdegree": 0,
    "scale": 0.5,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0294737,
        "red": 0,
        "green": 66,
        "blue": 113
      },
      {
        "position": 0.0652632,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.115789,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.187368,
        "red": 0,
        "green": 80,
        "blue": 145
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Origami",
    "alpha": -2.5,
    "betha": 0,
    "gamma": 0.9,
    "delta": 0,
    "omega": 0,
    "lambda": 2.409,
    "degree": 4,
    "npdegree": 0,
    "scale": 0.43,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0210526,
        "red": 0,
        "green": 120,
        "blue": 0
      },
      {
        "position": 0.0568421,
        "red": 178,
        "green": 218,
        "blue": 56
      },
      {
        "position": 0.0926316,
        "red": 175,
        "green": 34,
        "blue": 58
      },
      {
        "position": 0.107368,
        "red": 83,
        "green": 44,
        "blue": 57
      },
      {
        "position": 0.166316,
        "red": 206,
        "green": 181,
        "blue": 221
      },
      {
        "position": 0.212632,
        "red": 34,
        "green": 132,
        "blue": 224
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Pendulum Swing",
    "alpha": 1.806,
    "betha": -0.85,
    "gamma": 1.8,
    "delta": 0,
    "omega": 0,
    "lambda": -1.9,
    "degree": 7,
    "npdegree": 0,
    "scale": 0.55,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.117895,
        "red": 221,
        "green": 171,
        "blue": 105
      },
      {
        "position": 0.149474,
        "red": 0,
        "green": 0,
        "blue": 95
      },
      {
        "position": 0.189474,
        "red": 98,
        "green": 137,
        "blue": 138
      },
      {
        "position": 0.223158,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.349474,
        "red": 68,
        "green": 68,
        "blue": 68
      },
      {
        "position": 1,
        "red": 0,
        "green": 0,
        "blue": 0
      }
    ]
  },
  {
    "name": "Pentagon Burst",
    "alpha": 8,
    "betha": -0.7,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.5,
    "degree": 5,
    "npdegree": 0,
    "scale": 0.87,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.109474,
        "red": 12,
        "green": 12,
        "blue": 12
      },
      {
        "position": 0.124211,
        "red": 142,
        "green": 142,
        "blue": 142
      },
      {
        "position": 0.143158,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.170526,
        "red": 0,
        "green": 0,
        "blue": 71
      },
      {
        "position": 0.195789,
        "red": 255,
        "green": 97,
        "blue": 12
      },
      {
        "position": 0.233684,
        "red": 239,
        "green": 251,
        "blue": 11
      },
      {
        "position": 0.56,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Square Icon",
    "alpha": 5,
    "betha": 1.5,
    "gamma": 1,
    "delta": 0,
    "omega": 0,
    "lambda": -2.7,
    "degree": 4,
    "npdegree": 0,
    "scale": 0.7,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0505263,
        "red": 0,
        "green": 221,
        "blue": 74
      },
      {
        "position": 0.0673684,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.0926316,
        "red": 177,
        "green": 255,
        "blue": 99
      },
      {
        "position": 0.113684,
        "red": 255,
        "green": 255,
        "blue": 255
      },
      {
        "position": 0.145263,
        "red": 0,
        "green": 149,
        "blue": 92
      },
      {
        "position": 0.330526,
        "red": 209,
        "green": 236,
        "blue": 239
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Two Triangles",
    "alpha": -2.5,
    "betha": -0.9,
    "gamma": 0.9,
    "delta": 0,
    "omega": 0,
    "lambda": 2.4,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.43,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0736842,
        "red": 255,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.12,
        "red": 205,
        "green": 184,
        "blue": 178
      },
      {
        "position": 0.162105,
        "red": 168,
        "green": 113,
        "blue": 40
      },
      {
        "position": 0.225263,
        "red": 26,
        "green": 123,
        "blue": 140
      },
      {
        "position": 0.406316,
        "red": 171,
        "green": 207,
        "blue": 213
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Warrior's Shield",
    "alpha": 1.806,
    "betha": 0,
    "gamma": 1.5,
    "delta": 0,
    "omega": 0,
    "lambda": -1.806,
    "degree": 7,
    "npdegree": 0,
    "scale": 0.6,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0147368,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0736842,
        "red": 221,
        "green": 174,
        "blue": 22
      },
      {
        "position": 0.143158,
        "red": 12,
        "green": 91,
        "blue": 70
      },
      {
        "position": 0.286316,
        "red": 192,
        "green": 192,
        "blue": 229
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  },
  {
    "name": "Wingz",
    "alpha": -1,
    "betha": 0.1,
    "gamma": -0.82,
    "delta": 0,
    "omega": -0.3,
    "lambda": 1.56,
    "degree": 3,
    "npdegree": 0,
    "scale": 0.36,
    "palGamma": 0.5,
    "paletteData": [
      {
        "position": 0,
        "red": 0,
        "green": 0,
        "blue": 0
      },
      {
        "position": 0.0336842,
        "red": 0,
        "green": 255,
        "blue": 0
      },
      {
        "position": 0.0863158,
        "red": 14,
        "green": 142,
        "blue": 14
      },
      {
        "position": 0.136842,
        "red": 26,
        "green": 26,
        "blue": 148
      },
      {
        "position": 0.235789,
        "red": 196,
        "green": 196,
        "blue": 227
      },
      {
        "position": 0.492632,
        "red": 88,
        "green": 88,
        "blue": 96
      },
      {
        "position": 1,
        "red": 255,
        "green": 255,
        "blue": 255
      }
    ]
  }
]`;
var symmetricIconData = JSON.parse(symmetricIconDataString);
var Parametersets_default = symmetricIconData;

// src/attractors/shared/types.ts
var CONFIG = {
  DEFAULT_CANVAS_SIZE: 1800,
  ALIAS: 2,
  INITIAL_ICON_INDEX: 32,
  ITERATION_INTERVAL_MS: 500,
  COLOR_LUT_SIZE: 2048
};

// src/attractors/symmetricIcon/config.ts
var initialIcon = Parametersets_default[CONFIG.INITIAL_ICON_INDEX];
var DEFAULT_SYMMETRIC_ICON = {
  alpha: initialIcon.alpha,
  betha: initialIcon.betha,
  gamma: initialIcon.gamma,
  delta: initialIcon.delta,
  omega: initialIcon.omega,
  lambda: initialIcon.lambda,
  degree: initialIcon.degree,
  npdegree: initialIcon.npdegree,
  scale: initialIcon.scale
};

// src/attractors/symmetricIcon/meta.ts
var symmetricIconMeta = {
  id: "symmetric_icon",
  label: "Symmetric Icon",
  category: "Attractors",
  defaultParams: DEFAULT_SYMMETRIC_ICON,
  paramRanges: {
    lambda: { min: -2.5, max: 2.5 },
    alpha: { min: -2.5, max: 2.5 },
    betha: { min: -2.5, max: 2.5 },
    gamma: { min: -2.5, max: 2.5 },
    omega: { min: -0.5, max: 0.5 },
    delta: { min: -1, max: 1 },
    degree: { min: 3, max: 12, step: 1 },
    npdegree: { min: 0, max: 2, step: 1 }
  },
  workerIteratorName: "symmetric_icon",
  math: `
const xpos = p[0], ypos = p[1];
const zzbar = xpos * xpos + ypos * ypos;
let zz, zc = 0, zd = 0, zreal, zimag, za, zb, zn;

if (params.delta !== 0) {
  zz = Math.sqrt(zzbar);
  zc = 1; zd = 0;
  zreal = xpos / zz; zimag = ypos / zz;
  for (let j = 0; j < params.npdegree * params.degree; j++) {
    za = zc * zreal - zd * zimag;
    zb = zd * zreal + zc * zimag;
    zc = za; zd = zb;
  }
} else {
  zz = 0;
}

zreal = xpos; zimag = ypos;
for (let i = 0; i < params.degree - 2; i++) {
  za = zreal * xpos - zimag * ypos;
  zb = zimag * xpos + zreal * ypos;
  zreal = za; zimag = zb;
}

zn = xpos * zreal - ypos * zimag;
const factor = params.lambda + params.alpha * zzbar + params.betha * zn + params.delta * zz * zc;

p[0] = factor * xpos + params.gamma * zreal - params.omega * ypos;
p[1] = factor * ypos - params.gamma * zimag + params.omega * xpos;
`
};

// src/attractors/symmetricQuilt/config.ts
var DEFAULT_SYMMETRIC_QUILT = {
  lambda: 0.9,
  alpha: -0.6,
  beta: 0.1,
  gamma: -0.4,
  omega: 0,
  m: 0.9,
  shift: 0,
  scale: 1
};

// src/attractors/symmetricQuilt/meta.ts
var symmetricQuiltMeta = {
  id: "symmetric_quilt",
  label: "Symmetric Quilt",
  category: "Attractors",
  defaultParams: DEFAULT_SYMMETRIC_QUILT,
  paramRanges: {
    lambda: { min: -1, max: 1 },
    alpha: { min: -1, max: 1 },
    beta: { min: -1, max: 1 },
    gamma: { min: -1, max: 1 },
    omega: { min: -1, max: 1 },
    m: { min: 1, max: 3, step: 1 }
  },
  workerIteratorName: "symmetric_quilt",
  math: `
let x = p[0] + 0.5, y = p[1] + 0.5;
x = x - Math.floor(x); y = y - Math.floor(y);
const PI2 = Math.PI * 2;
const PI4 = Math.PI * 4;
const PI6 = Math.PI * 6;
const sin2pix = Math.sin(PI2 * x), sin2piy = Math.sin(PI2 * y);
const cos2pix = Math.cos(PI2 * x), cos2piy = Math.cos(PI2 * y);

let nx = params.m * x + params.shift + params.lambda * sin2pix - params.omega * sin2piy + 
         params.alpha * sin2pix * cos2piy + params.beta * Math.sin(PI4 * x) + 
         params.gamma * Math.sin(PI6 * x) * Math.cos(PI4 * y);
         
let ny = params.m * y + params.shift + params.lambda * sin2piy - params.omega * sin2pix + 
         params.alpha * sin2piy * cos2pix + params.beta * Math.sin(PI4 * y) + 
         params.gamma * Math.sin(PI6 * y) * Math.cos(PI4 * x);

nx = nx - Math.floor(nx); ny = ny - Math.floor(ny);
p[0] = nx - 0.5; p[1] = ny - 0.5;
`
};

// src/attractors/clifford/meta.ts
var cliffordMeta = {
  id: "clifford",
  label: "Clifford",
  category: "Attractors",
  defaultParams: { alpha: 1.5, beta: -1.8, gamma: 1.6, delta: 2, scale: 0.2 },
  paramRanges: {
    alpha: { min: -3, max: 3 },
    beta: { min: -3, max: 3 },
    gamma: { min: -3, max: 3 },
    delta: { min: -3, max: 3 }
  },
  workerIteratorName: "clifford_iterator",
  math: `
    const x = p[0], y = p[1];
    p[0] = Math.sin(params.alpha * y) + params.gamma * Math.cos(params.alpha * x);
    p[1] = Math.sin(params.beta * x) + params.delta * Math.cos(params.beta * y);
  `
};

// src/attractors/deJong/config.ts
var DEFAULT_DEJONG = {
  alpha: -2,
  beta: -2,
  gamma: -1.2,
  delta: 2,
  scale: 0.4
};

// src/attractors/deJong/meta.ts
var deJongMeta = {
  id: "dejong",
  label: "De Jong",
  category: "Attractors",
  defaultParams: DEFAULT_DEJONG,
  paramRanges: {
    alpha: { min: -3, max: 3 },
    beta: { min: -3, max: 3 },
    gamma: { min: -3, max: 3 },
    delta: { min: -3, max: 3 }
  },
  workerIteratorName: "dejong_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = Math.sin(params.alpha * y) - Math.cos(params.beta * x);
p[1] = Math.sin(params.gamma * x) - Math.cos(params.delta * y);
`
};

// src/attractors/tinkerbell/config.ts
var DEFAULT_TINKERBELL = {
  alpha: 0.9,
  beta: -0.6013,
  gamma: 2,
  delta: 0.5,
  scale: 0.15
};

// src/attractors/tinkerbell/meta.ts
var tinkerbellMeta = {
  id: "tinkerbell",
  label: "Tinkerbell",
  category: "Attractors",
  defaultParams: DEFAULT_TINKERBELL,
  paramRanges: {
    alpha: { min: 0.7, max: 1.1 },
    beta: { min: -0.8, max: -0.4 },
    gamma: { min: 1.8, max: 2.2 },
    delta: { min: 0.3, max: 0.7 }
  },
  workerIteratorName: "tinkerbell_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = x * x - y * y + params.alpha * x + params.beta * y;
p[1] = 2 * x * y + params.gamma * x + params.delta * y;
`
};

// src/attractors/henon/config.ts
var DEFAULT_HENON = {
  alpha: 1.4,
  beta: 0.3,
  scale: 0.5
};

// src/attractors/henon/meta.ts
var henonMeta = {
  id: "henon",
  label: "Henon",
  category: "Attractors",
  defaultParams: DEFAULT_HENON,
  paramRanges: {
    alpha: { min: 1, max: 1.4 },
    beta: { min: 0.2, max: 0.4 }
  },
  workerIteratorName: "henon_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = 1 - params.alpha * x * x + y;
p[1] = params.beta * x;
`
};

// src/attractors/bedhead/config.ts
var DEFAULT_BEDHEAD = {
  alpha: -0.81,
  beta: -0.92,
  scale: 0.3
};

// src/attractors/bedhead/meta.ts
var bedheadMeta = {
  id: "bedhead",
  label: "Bedhead",
  category: "Attractors",
  defaultParams: DEFAULT_BEDHEAD,
  paramRanges: {
    alpha: { min: -2, max: 2 },
    beta: { min: -2, max: 2 }
  },
  workerIteratorName: "bedhead_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = Math.sin((x * y) / params.beta) * y + Math.cos(params.alpha * x - y);
p[1] = x + Math.sin(y) / params.beta;
`
};

// src/attractors/svensson/config.ts
var DEFAULT_SVENSSON = {
  alpha: 1.4,
  beta: 1.56,
  gamma: 1.4,
  delta: -6.56,
  scale: 0.15
};

// src/attractors/svensson/meta.ts
var svenssonMeta = {
  id: "svensson",
  label: "Svensson",
  category: "Attractors",
  defaultParams: DEFAULT_SVENSSON,
  paramRanges: {
    alpha: { min: -2.5, max: 2.5 },
    beta: { min: -2.5, max: 2.5 },
    gamma: { min: -2.5, max: 2.5 },
    delta: { min: -2.5, max: 2.5 }
  },
  workerIteratorName: "svensson_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = params.delta * Math.sin(params.alpha * x) - Math.sin(params.beta * y);
p[1] = params.gamma * Math.cos(params.alpha * x) + Math.cos(params.beta * y);
`
};

// src/attractors/fractalDream/config.ts
var DEFAULT_FRACTAL_DREAM = {
  alpha: -0.966918,
  beta: 2.879879,
  gamma: 0.765145,
  delta: 0.744728,
  scale: 0.35
};

// src/attractors/fractalDream/meta.ts
var fractalDreamMeta = {
  id: "fractal_dream",
  label: "Fractal Dream",
  category: "Attractors",
  defaultParams: DEFAULT_FRACTAL_DREAM,
  paramRanges: {
    alpha: { min: -3, max: 3 },
    beta: { min: -3, max: 3 },
    gamma: { min: -1, max: 1 },
    delta: { min: -1, max: 1 }
  },
  workerIteratorName: "fractal_dream_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = Math.sin(y * params.beta) + params.gamma * Math.sin(x * params.beta);
p[1] = Math.sin(x * params.alpha) + params.delta * Math.sin(y * params.alpha);
`
};

// src/attractors/hopalong/config.ts
var DEFAULT_HOPALONG = {
  alpha: 2,
  beta: 1,
  gamma: 0,
  scale: 8e-3
};

// src/attractors/hopalong/meta.ts
var hopalongMeta = {
  id: "hopalong",
  label: "Hopalong",
  category: "Attractors",
  defaultParams: DEFAULT_HOPALONG,
  paramRanges: {
    alpha: { min: -10, max: 10 },
    beta: { min: -10, max: 10 },
    gamma: { min: -10, max: 10 }
  },
  workerIteratorName: "hopalong_iterator",
  math: `
const x = p[0], y = p[1];
const sign = x >= 0 ? 1 : -1;
p[0] = y - sign * Math.sqrt(Math.abs(params.beta * x - params.gamma));
p[1] = params.alpha - x;
`
};

// src/attractors/gumowskiMira/config.ts
var DEFAULT_GUMOWSKI_MIRA = {
  mu: -0.7,
  alpha: 8e-3,
  sigma: 0.05,
  scale: 0.04
};

// src/attractors/gumowskiMira/meta.ts
var gumowskiMiraMeta = {
  id: "gumowski_mira",
  label: "Gumowski-Mira",
  category: "Attractors",
  defaultParams: DEFAULT_GUMOWSKI_MIRA,
  paramRanges: {
    alpha: { min: -0.1, max: 0.1 },
    sigma: { min: 0.01, max: 0.1 },
    mu: { min: -1, max: 1 }
  },
  workerIteratorName: "gumowski_mira_iterator",
  math: `
const f = (x) => params.mu * x + (2 * (1 - params.mu) * x * x) / (1 + x * x);
const x = p[0], y = p[1];
const fx = f(x);
const nx = y + params.alpha * (1 - params.sigma * y * y) * y + fx;
p[0] = nx;
p[1] = -x + f(nx);
`
};

// src/attractors/sprott/config.ts
var DEFAULT_SPROTT = {
  a1: 1,
  a2: -0.1,
  a3: 0.9,
  a4: -0.5,
  a5: -0.6,
  a6: -1.1,
  a7: -0.3,
  a8: -0.1,
  a9: -0.3,
  a10: -0.6,
  a11: 0.8,
  a12: -0.5,
  scale: 0.2
};

// src/attractors/sprott/meta.ts
var sprottMeta = {
  id: "sprott",
  label: "Sprott",
  category: "Attractors",
  defaultParams: DEFAULT_SPROTT,
  paramRanges: {
    a1: { min: -1.2, max: 1.2 },
    a2: { min: -1.2, max: 1.2 },
    a3: { min: -1.2, max: 1.2 },
    a4: { min: -1.2, max: 1.2 },
    a5: { min: -1.2, max: 1.2 },
    a6: { min: -1.2, max: 1.2 },
    a7: { min: -1.2, max: 1.2 },
    a8: { min: -1.2, max: 1.2 },
    a9: { min: -1.2, max: 1.2 },
    a10: { min: -1.2, max: 1.2 },
    a11: { min: -1.2, max: 1.2 },
    a12: { min: -1.2, max: 1.2 }
  },
  workerIteratorName: "sprott_iterator",
  math: `
const x = p[0], y = p[1];
p[0] = params.a1 + params.a2*x + params.a3*x*x + params.a4*x*y + params.a5*y + params.a6*y*y;
p[1] = params.a7 + params.a8*x + params.a9*x*x + params.a10*x*y + params.a11*y + params.a12*y*y;
`
};

// src/attractors/symmetricFractal/config.ts
var DEFAULT_SYMMETRIC_FRACTAL = {
  a: 0.5,
  b: 0,
  c: 0,
  d: 0.5,
  alpha: 0.5,
  beta: 0,
  p: 3,
  reflect: true,
  scale: 0.3
};

// src/attractors/symmetricFractal/meta.ts
var symmetricFractalMeta = {
  id: "symmetric_fractal",
  label: "Symmetric Fractal",
  category: "IFS",
  defaultParams: DEFAULT_SYMMETRIC_FRACTAL,
  paramRanges: {
    a: { min: -1, max: 1 },
    b: { min: -1, max: 1 },
    c: { min: -1, max: 1 },
    d: { min: -1, max: 1 },
    alpha: { min: -0.5, max: 0.5 },
    beta: { min: -0.5, max: 0.5 },
    p: { min: 3, max: 12, step: 1 }
  },
  workerIteratorName: "symmetric_fractal_iterator",
  math: `
const x = p[0], y = p[1];
let nx = params.a * x + params.b * y + params.alpha;
let ny = params.c * x + params.d * y + params.beta;
const angle = (2 * Math.PI * Math.floor(Math.random() * params.p)) / params.p;
const cos = Math.cos(angle), sin = Math.sin(angle);
let rx = nx * cos - ny * sin;
let ry = nx * sin + ny * cos;
if (params.reflect && Math.random() < 0.5) rx = -rx;
p[0] = rx; p[1] = ry;
`
};

// src/attractors/deRham/config.ts
var DEFAULT_DERHAM = {
  alpha: 0.5,
  beta: 0.5,
  curveType: "cesaro",
  scale: 0.4
};

// src/attractors/deRham/meta.ts
var deRhamMeta = {
  id: "derham",
  label: "De Rham",
  category: "IFS",
  defaultParams: DEFAULT_DERHAM,
  workerIteratorName: "derham_iterator",
  math: `
const x = p[0], y = p[1];
const choice = Math.random() < 0.5 ? 0 : 1;

if (params.curveType === "cesaro") {
  if (choice === 0) {
    p[0] = params.alpha * x - params.beta * y; p[1] = params.alpha * y + params.beta * x;
  } else {
    const ra = 1 - params.alpha, rb = -params.beta;
    p[0] = params.alpha + ra * x - rb * y; p[1] = params.beta + ra * y + rb * x;
  }
} else if (params.curveType === "koch") {
  if (choice === 0) {
    p[0] = params.alpha * x + params.beta * y; p[1] = -params.alpha * y + params.beta * x;
  } else {
    const ra = 1 - params.alpha, rb = -params.beta;
    p[0] = params.alpha + ra * x + rb * y; p[1] = params.beta - ra * y + rb * x;
  }
} else {
  if (choice === 0) {
    p[0] = params.alpha * x - params.beta * y; p[1] = params.beta * x + params.alpha * y;
  } else {
    p[0] = params.alpha + (1-params.alpha) * x + params.beta * y; p[1] = params.beta + -params.beta * x + (1-params.alpha) * y;
  }
}
`
};

// src/attractors/conradi/config.ts
var DEFAULT_CONRADI = {
  r1: 0.5,
  theta1: 0.3,
  r2: 0.5,
  theta2: 0.7,
  a: 0.1,
  n: 5,
  variant: 1,
  scale: 0.25
};

// src/attractors/conradi/meta.ts
var conradiMeta = {
  id: "conradi",
  label: "Conradi",
  category: "Attractors",
  defaultParams: DEFAULT_CONRADI,
  workerIteratorName: "conradi_iterator",
  math: `
const x = p[0], y = p[1];
let zr, zi;
const c1r = params.r1 * Math.cos(params.theta1 * Math.PI);
const c1i = params.r1 * Math.sin(params.theta1 * Math.PI);
const c2r = params.r2 * Math.cos(params.theta2 * Math.PI);
const c2i = params.r2 * Math.sin(params.theta2 * Math.PI);

if (params.variant === 1) {
  const denom = x*x + y*y + 0.0001;
  const invr = x / denom, invi = -y / denom;
  zr = (c1r * invr - c1i * invi) + (c2r * x + c2i * y) + params.a;
  zi = (c1r * invi + c1i * invr) + (c2r * y - c2i * x);
} else {
  const denom = x*x + y*y + 0.0001;
  const dr = (c1r * x - c1i * y) + (c2r * x + c2i * y) / denom + params.a;
  const di = (c1r * y + c1i * x) + (c2r * y - c2i * x) / denom;
  const d2 = dr*dr + di*di + 0.0001;
  zr = dr / d2; zi = -di / d2;
}
const angle = (2 * Math.PI * Math.floor(Math.random() * params.n)) / params.n;
const cos = Math.cos(angle), sin = Math.sin(angle);
p[0] = zr * cos - zi * sin; p[1] = zr * sin + zi * cos;
`
};

// src/attractors/mobius/config.ts
var DEFAULT_MOBIUS = {
  aRe: 0.5,
  aIm: 0.5,
  bRe: 0.3,
  bIm: 0.2,
  cRe: 0.1,
  cIm: 0.1,
  dRe: 0.6,
  dIm: 0.3,
  n: 5,
  scale: 0.3
};

// src/attractors/mobius/meta.ts
var mobiusMeta = {
  id: "mobius",
  label: "Mobius",
  category: "IFS",
  defaultParams: DEFAULT_MOBIUS,
  workerIteratorName: "mobius_iterator",
  math: `
const x = p[0], y = p[1];
const numr = params.aRe * x - params.aIm * y + params.bRe;
const numi = params.aRe * y + params.aIm * x + params.bi; // Wait, worker has this.bi, but params has bIm
const denr = params.cRe * x - params.cIm * y + params.dr; // Wait, worker has this.dr, but params has dRe
const deni = params.cRe * y + params.cIm * x + params.di; // Wait, worker has this.di, but params has dIm
const d2 = denr * denr + deni * deni + 0.0001;
const zr = (numr * denr + numi * deni) / d2;
const zi = (numi * denr - numr * deni) / d2;
const angle = (2 * Math.PI * Math.floor(Math.random() * params.n)) / params.n;
const cos = Math.cos(angle), sin = Math.sin(angle);
p[0] = zr * cos - zi * sin; p[1] = zr * sin + zi * cos;
`
};

// src/attractors/mandelbrot/config.ts
var DEFAULT_MANDELBROT = {
  centerX: -0.5,
  centerY: 0,
  zoom: 1,
  maxIter: 256
};

// src/attractors/mandelbrot/meta.ts
var mandelbrotMeta = {
  id: "mandelbrot",
  label: "Mandelbrot",
  category: "Fractals",
  defaultParams: DEFAULT_MANDELBROT,
  workerIteratorName: "mandelbrot"
};

// src/attractors/julia/config.ts
var DEFAULT_JULIA = {
  cReal: -0.7,
  cImag: 0.27015,
  centerX: 0,
  centerY: 0,
  zoom: 1,
  maxIter: 256
};

// src/attractors/julia/meta.ts
var juliaMeta = {
  id: "julia",
  label: "Julia",
  category: "Fractals",
  defaultParams: DEFAULT_JULIA,
  workerIteratorName: "julia"
};

// src/attractors/burningship/config.ts
var DEFAULT_BURNING_SHIP = {
  centerX: -0.4,
  centerY: -0.6,
  zoom: 1,
  maxIter: 256
};

// src/attractors/burningship/meta.ts
var burningshipMeta = {
  id: "burningship",
  label: "Burning Ship",
  category: "Fractals",
  defaultParams: DEFAULT_BURNING_SHIP,
  workerIteratorName: "burningship"
};

// src/attractors/tricorn/config.ts
var DEFAULT_TRICORN = {
  centerX: 0,
  centerY: 0,
  zoom: 1,
  maxIter: 256
};

// src/attractors/tricorn/meta.ts
var tricornMeta = {
  id: "tricorn",
  label: "Tricorn",
  category: "Fractals",
  defaultParams: DEFAULT_TRICORN,
  workerIteratorName: "tricorn"
};

// src/attractors/multibrot/config.ts
var DEFAULT_MULTIBROT = {
  centerX: 0,
  centerY: 0,
  zoom: 1,
  maxIter: 256,
  power: 3
};

// src/attractors/multibrot/meta.ts
var multibrotMeta = {
  id: "multibrot",
  label: "Multibrot",
  category: "Fractals",
  defaultParams: DEFAULT_MULTIBROT,
  workerIteratorName: "multibrot"
};

// src/attractors/newton/config.ts
var DEFAULT_NEWTON = {
  centerX: 0,
  centerY: 0,
  zoom: 1,
  maxIter: 64
};

// src/attractors/newton/meta.ts
var newtonMeta = {
  id: "newton",
  label: "Newton",
  category: "Fractals",
  defaultParams: DEFAULT_NEWTON,
  workerIteratorName: "newton"
};

// src/attractors/phoenix/config.ts
var DEFAULT_PHOENIX = {
  centerX: 0,
  centerY: 0,
  zoom: 1,
  maxIter: 256,
  cReal: 0.5667,
  cImag: 0,
  p: -0.5
};

// src/attractors/phoenix/meta.ts
var phoenixMeta = {
  id: "phoenix",
  label: "Phoenix",
  category: "Fractals",
  defaultParams: DEFAULT_PHOENIX,
  workerIteratorName: "phoenix"
};

// src/attractors/lyapunov/config.ts
var DEFAULT_LYAPUNOV = {
  aMin: 2,
  aMax: 4,
  bMin: 2,
  bMax: 4,
  maxIter: 100,
  sequence: "AB"
};

// src/attractors/lyapunov/meta.ts
var lyapunovMeta = {
  id: "lyapunov",
  label: "Lyapunov",
  category: "Fractals",
  defaultParams: DEFAULT_LYAPUNOV,
  workerIteratorName: "lyapunov"
};

// src/attractors/catalog.ts
var SYSTEM_CATALOG = [
  symmetricIconMeta,
  symmetricQuiltMeta,
  cliffordMeta,
  deJongMeta,
  tinkerbellMeta,
  henonMeta,
  bedheadMeta,
  svenssonMeta,
  fractalDreamMeta,
  hopalongMeta,
  gumowskiMiraMeta,
  sprottMeta,
  symmetricFractalMeta,
  deRhamMeta,
  conradiMeta,
  mobiusMeta,
  mandelbrotMeta,
  juliaMeta,
  burningshipMeta,
  tricornMeta,
  multibrotMeta,
  newtonMeta,
  phoenixMeta,
  lyapunovMeta
];
function getSystemMeta(id) {
  return SYSTEM_CATALOG.find((s) => s.id === id);
}

// src/seo/ogParams.ts
var MAX_FRACTAL_ITER = 2e3;
var MAX_LYAPUNOV_ITER = 500;
var LYAPUNOV_SEQUENCE = /^[AB]{1,32}$/;
var FRACTAL_RANGES = {
  centerX: { min: -4, max: 4 },
  centerY: { min: -4, max: 4 },
  zoom: { min: 0.01, max: 1e13 },
  cReal: { min: -4, max: 4 },
  cImag: { min: -4, max: 4 },
  p: { min: -4, max: 4 },
  power: { min: 2, max: 12 },
  aMin: { min: 0, max: 4.5 },
  aMax: { min: 0, max: 4.5 },
  bMin: { min: 0, max: 4.5 },
  bMax: { min: 0, max: 4.5 }
};
function parseShareParams(search) {
  const type = search.get("type");
  const meta = type ? getSystemMeta(type) : void 0;
  if (!meta) return null;
  const params = { ...meta.defaultParams };
  for (const key of Object.keys(params)) {
    const raw = search.get(key);
    if (raw === null) continue;
    if (typeof params[key] === "number") {
      const num = parseFloat(raw);
      if (!Number.isFinite(num)) continue;
      const range = meta.paramRanges?.[key] ?? (meta.category === "Fractals" ? FRACTAL_RANGES[key] : void 0);
      params[key] = range ? Math.min(range.max, Math.max(range.min, num)) : num;
    } else if (key === "sequence") {
      if (LYAPUNOV_SEQUENCE.test(raw)) params[key] = raw;
    } else if (typeof params[key] === "string") {
      params[key] = raw;
    }
  }
  if (meta.category === "Fractals" && typeof params.maxIter === "number") {
    const cap = meta.id === "lyapunov" ? MAX_LYAPUNOV_ITER : MAX_FRACTAL_ITER;
    params.maxIter = Math.max(1, Math.min(cap, Math.round(params.maxIter)));
  }
  return { meta, params };
}
function shareQuery({ meta, params }) {
  const q = new URLSearchParams({ type: meta.id });
  for (const [key, value] of Object.entries(params)) q.set(key, String(value));
  return q.toString();
}

// src/seo/ogRender.ts
var import_fs = __toESM(require("fs"));
var import_path = __toESM(require("path"));
var import_vm = __toESM(require("vm"));
var import_sharp = __toESM(require("sharp"));
var CARD_WIDTH = 1200;
var CARD_HEIGHT = 630;
var RENDER_SIZE = 630;
var BACKGROUND = { r: 11, g: 13, b: 20 };
var CARD_MAX_ITER = 1e3;
var root = () => process.cwd();
var workerScript = null;
function getWorkerScript() {
  if (!workerScript) {
    const source = import_fs.default.readFileSync(import_path.default.join(root(), "public/worker.js"), "utf8");
    workerScript = new import_vm.default.Script(source, { filename: "worker.js" });
  }
  return workerScript;
}
function seededRandom(seed) {
  let a = seed >>> 0;
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
var StubCanvas = class {
  constructor(width, height) {
    this.width = width;
    this.height = height;
    this.pixels = new Uint8ClampedArray(width * height * 4);
    this.ctx = new StubContext(this);
  }
  getContext() {
    return this.ctx;
  }
  convertToBlob() {
    return Promise.resolve(null);
  }
};
var StubContext = class {
  constructor(canvas) {
    this.canvas = canvas;
    this.fillStyle = "rgb(0, 0, 0)";
    this.imageSmoothingEnabled = true;
    this.imageSmoothingQuality = "low";
  }
  createImageData(w, h) {
    return { data: new Uint8ClampedArray(w * h * 4), width: w, height: h };
  }
  putImageData(img, dx, dy, x = 0, y = 0, w = img.width, h = img.height) {
    const { pixels, width, height } = this.canvas;
    for (let row = y; row < y + h; row++) {
      const ty = dy + row;
      if (ty < 0 || ty >= height) continue;
      const cols = Math.min(w, width - (dx + x));
      const src = (row * img.width + x) * 4;
      pixels.set(img.data.subarray(src, src + cols * 4), (ty * width + dx + x) * 4);
    }
  }
  fillRect(x, y, w, h) {
    const m = /rgb\((\d+),\s*(\d+),\s*(\d+)\)/.exec(this.fillStyle);
    const [r, g, b] = m ? [+m[1], +m[2], +m[3]] : [0, 0, 0];
    const { pixels, width, height } = this.canvas;
    for (let py = Math.max(0, y); py < Math.min(height, y + h); py++) {
      for (let px = Math.max(0, x); px < Math.min(width, x + w); px++) {
        const i = (py * width + px) * 4;
        pixels[i] = r;
        pixels[i + 1] = g;
        pixels[i + 2] = b;
        pixels[i + 3] = 255;
      }
    }
  }
  /** Only used to upscale the fractal preview to the full canvas (nearest neighbour). */
  drawImage(src, dx, dy, dw = src.width, dh = src.height) {
    const { pixels, width } = this.canvas;
    for (let py = 0; py < dh; py++) {
      const sy = Math.min(src.height - 1, Math.floor(py * src.height / dh));
      for (let px = 0; px < dw; px++) {
        const sx = Math.min(src.width - 1, Math.floor(px * src.width / dw));
        const s = (sy * src.width + sx) * 4;
        const d = ((dy + py) * width + dx + px) * 4;
        pixels[d] = src.pixels[s];
        pixels[d + 1] = src.pixels[s + 1];
        pixels[d + 2] = src.pixels[s + 2];
        pixels[d + 3] = 255;
      }
    }
  }
};
function renderSystemPixels(meta, params, opts = {}) {
  const { budgetMs = 1500, passes = 40, fractalBudgetMs = 8e3 } = opts;
  const timers = [];
  const sandboxMath = Object.create(Math);
  sandboxMath.random = seededRandom(24301);
  const sandbox = {
    console,
    Math: sandboxMath,
    Float64Array,
    Uint32Array,
    Uint16Array,
    Uint8ClampedArray,
    Array,
    Object,
    Number,
    isNaN,
    isFinite,
    Promise,
    OffscreenCanvas: StubCanvas,
    performance: { now: () => performance.now() },
    // Timers run synchronously (in order) from the drain loop below.
    setTimeout: (fn) => {
      timers.push(fn);
      return timers.length;
    },
    clearTimeout: () => {
    },
    postMessage: () => {
    }
  };
  sandbox.self = sandbox;
  import_vm.default.createContext(sandbox);
  getWorkerScript().runInContext(sandbox);
  const send = (type, payload) => sandbox.onmessage({ data: { type, payload } });
  const canvas = new StubCanvas(RENDER_SIZE, RENDER_SIZE);
  const isFractal = meta.category === "Fractals";
  const startup = Parametersets_default[CONFIG.INITIAL_ICON_INDEX];
  const iterator = {
    name: meta.workerIteratorName || meta.id,
    parameters: meta.category === "Fractals" && typeof params.maxIter === "number" ? { ...params, maxIter: Math.min(CARD_MAX_ITER, params.maxIter) } : { ...params },
    math: meta.math
  };
  if (meta.id === "lyapunov" && params.sequence) iterator.sequence = params.sequence;
  const started = performance.now();
  send("initialize", {
    // Fractals skip supersampling: at card size it is invisible and costs 4× the time.
    mode: "offscreen",
    canvas,
    size: RENDER_SIZE,
    alias: isFractal ? 1 : CONFIG.ALIAS,
    scale: isFractal ? 1 : Number(params.scale ?? 1),
    palette: startup.paletteData,
    colorLUTSize: CONFIG.COLOR_LUT_SIZE,
    palGamma: startup.palGamma ?? 0.5,
    palScale: true,
    palMax: 1e4,
    bgColor: { r: 0, g: 0, b: 0 },
    iterator
  });
  if (isFractal) {
    while (timers.length && performance.now() - started < fractalBudgetMs) timers.shift()();
  } else {
    for (let pass = 0; pass < passes; pass++) {
      if (pass > 0 && performance.now() - started >= budgetMs) break;
      send("iterate", {});
    }
  }
  return canvas.pixels;
}
var escapeMarkup = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
var fontFile = (weight) => import_path.default.join(root(), `node_modules/katex/dist/fonts/KaTeX_SansSerif-${weight}.ttf`);
function textLayer(markup, weight, width) {
  return (0, import_sharp.default)({
    text: { text: markup, font: `KaTeX_SansSerif ${weight}`, fontfile: fontFile(weight), rgba: true, width, dpi: 72, wrap: "word" }
  }).png().toBuffer();
}
async function renderShareImage(meta, params, opts = {}) {
  const pixels = renderSystemPixels(meta, params, opts);
  const render = await (0, import_sharp.default)(Buffer.from(pixels.buffer, pixels.byteOffset, pixels.byteLength), {
    raw: { width: RENDER_SIZE, height: RENDER_SIZE, channels: 4 }
  }).removeAlpha().png().toBuffer();
  const textWidth = CARD_WIDTH - RENDER_SIZE - 120;
  const [brand, label, tagline, url] = await Promise.all([
    textLayer(`<span foreground="#a5b4fc" size="22pt" letter_spacing="2048">CHAOS ITERATOR</span>`, "Bold", textWidth),
    textLayer(`<span foreground="#ffffff" size="54pt">${escapeMarkup(meta.label)}</span>`, "Bold", textWidth),
    textLayer(`<span foreground="#c7cad6" size="24pt">${escapeMarkup(meta.category === "Fractals" ? "Fractal" : meta.category === "IFS" ? "Iterated function system" : "Strange attractor")} \xB7 rendered from this exact link</span>`, "Regular", textWidth),
    textLayer(`<span foreground="#8b90a3" size="20pt">chaos-iterator.vercel.app \u2014 make your own, free</span>`, "Regular", textWidth)
  ]);
  const left = RENDER_SIZE + 60;
  return (0, import_sharp.default)({ create: { width: CARD_WIDTH, height: CARD_HEIGHT, channels: 3, background: BACKGROUND } }).composite([
    { input: render, left: 0, top: 0 },
    { input: brand, left, top: 150 },
    { input: label, left, top: 200 },
    { input: tagline, left, top: 300 },
    { input: url, left, top: CARD_HEIGHT - 90 }
  ]).png().toBuffer();
}

// src/server/og.ts
var IMMUTABLE = "public, max-age=31536000, s-maxage=31536000, immutable";
async function GET(request) {
  const url = new URL(request.url);
  const share = parseShareParams(url.searchParams);
  if (!share) return new Response("Unknown system", { status: 404, headers: { "Content-Type": "text/plain" } });
  const canonical = shareQuery(share);
  if (url.search.slice(1) !== canonical) {
    return new Response(null, {
      status: 308,
      headers: { Location: new URL(`/api/og?${canonical}`, url).toString(), "Cache-Control": IMMUTABLE }
    });
  }
  const png = await renderShareImage(share.meta, share.params);
  return new Response(new Uint8Array(png), {
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": IMMUTABLE
    }
  });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  GET
});
